/*
 * Gonitorix - a system and network monitoring tool
 * Copyright (C) 2026 Daniel Armbrust <darmbrust@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
 
package process

import (
	"os"
	"fmt"
	"context"
	"strconv"
	"math"
	
	"gonitorix/internal/config"
	"gonitorix/internal/logging"
	"gonitorix/internal/utils"
)

// sanitizeFloat ensures the value sent to RRD is valid.
// RRD does not accept NaN or Inf values.
func sanitizeFloat(v float64) float64 {
	if math.IsNaN(v) || math.IsInf(v, 0) {
		return 0
	}
	return v
}

func createRRD(ctx context.Context) {
	step := config.ProcessCfg.Step
	heartbeat := utils.Heartbeat(step)

	for _, processStat := range processHistory {			
		rrdFile := processStat.rrdFile

		select {
			case <-ctx.Done():
				return
			default:
		}

		if _, err := os.Stat(rrdFile); err == nil {
			logging.Info("PROCESS", "RRD '%s' already exists", rrdFile)
			continue
		}

		args := []string{
			"create", rrdFile,
			"--step", strconv.Itoa(step),

			// --------------------------------------------------
			// Data Sources
			// --------------------------------------------------

			// cpu  - CPU usage percentage of the monitored process (may exceed 100% on multi-core systems).
			// mem  - Memory usage of the monitored process (RSS or percentage, depending on implementation).
			// dsk  - Disk I/O rate generated by the process (read/write throughput per interval).
			// net  - Network I/O rate associated with the process (if calculated externally).
			// nof  - Number of open file descriptors held by the process.
			// pro  - Number of process instances or child processes being monitored.
			// nth  - Number of threads currently running within the process.
			// vcs  - Voluntary context switches rate for the process.
			// ics  - Involuntary context switches rate for the process.
			// upt  - Process uptime (time elapsed since the process started).
			// va2  - Secondary virtual memory metric (e.g., virtual memory size or custom virtual allocation metric).

			fmt.Sprintf("DS:cpu:GAUGE:%d:0:100", heartbeat),
			fmt.Sprintf("DS:mem:GAUGE:%d:0:U", heartbeat),
			fmt.Sprintf("DS:dsk:GAUGE:%d:0:U", heartbeat),
			fmt.Sprintf("DS:net:GAUGE:%d:0:U", heartbeat),
			fmt.Sprintf("DS:nof:GAUGE:%d:0:U", heartbeat),
			fmt.Sprintf("DS:pro:GAUGE:%d:0:U", heartbeat),
			fmt.Sprintf("DS:nth:GAUGE:%d:0:U", heartbeat),
			fmt.Sprintf("DS:vcs:GAUGE:%d:0:U", heartbeat),
			fmt.Sprintf("DS:ics:GAUGE:%d:0:U", heartbeat),
			fmt.Sprintf("DS:upt:GAUGE:%d:0:U", heartbeat),
			fmt.Sprintf("DS:va2:GAUGE:%d:0:U", heartbeat),
		}

		// ----------------------------
		// DAILY
		// ----------------------------
		dailyRows := utils.Rows(step, 1, utils.DaySeconds)

		args = append(args,
			utils.RRA("AVERAGE", 0.5, 1, dailyRows),
			utils.RRA("MIN", 0.5, 1, dailyRows),
			utils.RRA("MAX", 0.5, 1, dailyRows),
			utils.RRA("LAST", 0.5, 1, dailyRows),
		)

		// ----------------------------
		// WEEKLY
		// ----------------------------
		weeklyPDP := 30
		weeklyRows := utils.Rows(step, weeklyPDP, utils.WeekSeconds)

		args = append(args,
			utils.RRA("AVERAGE", 0.5, weeklyPDP, weeklyRows),
			utils.RRA("MIN", 0.5, weeklyPDP, weeklyRows),
			utils.RRA("MAX", 0.5, weeklyPDP, weeklyRows),
			utils.RRA("LAST", 0.5, weeklyPDP, weeklyRows),
		)

		// ----------------------------
		// MONTHLY
		// ----------------------------
		monthlyPDP := 60
		monthlyRows := utils.Rows(step, monthlyPDP, utils.MonthSeconds)

		args = append(args,
			utils.RRA("AVERAGE", 0.5, monthlyPDP, monthlyRows),
			utils.RRA("MIN", 0.5, monthlyPDP, monthlyRows),
			utils.RRA("MAX", 0.5, monthlyPDP, monthlyRows),
			utils.RRA("LAST", 0.5, monthlyPDP, monthlyRows),
		)

		// ----------------------------
		// YEARLY
		// ----------------------------
		yearlyPDP := 1440

		for n := 1; n <= config.ProcessCfg.MaxHistoricYears; n++ {
			duration := n * utils.YearSeconds
			rows := utils.Rows(step, yearlyPDP, duration)

			args = append(args,
				utils.RRA("AVERAGE", 0.5, yearlyPDP, rows),
				utils.RRA("MIN", 0.5, yearlyPDP, rows),
				utils.RRA("MAX", 0.5, yearlyPDP, rows),
				utils.RRA("LAST", 0.5, yearlyPDP, rows),
			)
		}

		if err := utils.ExecCommand(ctx, "PROCESS", "rrdtool", args...); err != nil {
			logging.Error("PROCESS", "Error creating RRD '%s'",	rrdFile)
			continue
		}

		logging.Info("PROCESS", "Created RRD '%s'",	rrdFile)
	}
}

func updateRRD(ctx context.Context, procName string, cpu float64, mem uint64, dsk float64,
	           net float64, nof float64, pro float64, nth float64, vcs float64, ics float64,
	           upt float64, va2 float64) error {
	
	rrdFile := processHistory[procName].rrdFile

	// Sanitize float values
	cpu = sanitizeFloat(cpu)
	dsk = sanitizeFloat(dsk)
	net = sanitizeFloat(net)
	vcs = sanitizeFloat(vcs)
	ics = sanitizeFloat(ics)
	upt = sanitizeFloat(upt)

	// Monitorix
	// $rrdata .= ":$cpu:$mem:$dsk:$net:$nof:$pro:$nth:$vcs:$ics:$upt:0";
	rrdata := fmt.Sprintf(
		"N:%.2f:%d:%.2f:%.2f:%.0f:%.0f:%.0f:%.2f:%.2f:%.0f:%.0f",
		cpu, mem, dsk, net, nof, pro, nth, vcs, ics, upt, va2,
	)

	if err := utils.ExecCommand(ctx, "PROCESS", "rrdtool", "update", rrdFile, rrdata); err != nil {
		logging.Error("PROCESS", "RRDTOOL update failed for %s: %v", rrdFile, err)
		return err
	}

	return nil
}